/* eslint-disable */
// Threat-model screen — provenance banner + STRIDE matrix + entries + coverage
// + trust-boundary surface map + supplied-vs-authored comparator. Omitted at the
// tab level (app.jsx) when data.threat_model.present is false.

function ThreatModel({ data }) {
  const tm = data.threat_model || {};
  const MATRIX_CLASS = { covered: "covered", gap: "gapped", partial: "partial", silent: "silent" };
  const MATRIX_LABEL = { covered: "covd", gap: "gap", partial: "part", silent: "—" };

  return (
    <div className="threat-model">
      <div className="section-eyebrow">§ Threat model — {tm.methodology ? tm.methodology.toUpperCase() : "model"}</div>
      <h2 className="section-title">Modeled threats · {tm.entry_count} entries · {tm.grounded_count} mitigated · {tm.gap_count} gaps</h2>

      {/* Provenance banner — reuses the attack-paths summary-banner inline style */}
      <div style={{
        fontFamily: "var(--font-mono)", fontSize: "var(--text-xs)", color: "var(--ink-3)",
        background: "var(--paper-2)", border: "1px solid var(--rule)", borderLeft: "3px solid var(--accent)",
        borderRadius: "0 var(--radius-sm) var(--radius-sm) 0", padding: "var(--space-2) var(--space-3)", lineHeight: 1.6,
      }}>
        <strong style={{ color: "var(--ink)" }}>
          {tm.authored ? "Authored baseline" : "User-supplied"}
        </strong>{" "}
        — generated by <code>{tm.generated_by}</code>
        {tm.source_artifact ? <> · grounded from <code>{tm.source_artifact}</code></> : null}
        {tm.comparator ? " · supplied-vs-authored comparator below" : null}
      </div>

      {/* A — STRIDE × asset matrix */}
      <section>
        <div className="section-eyebrow" style={{ marginTop: "var(--space-5)" }}>A — STRIDE × asset</div>
        <div style={{ overflowX: "auto" }}>
          <table className="apd-matrix">
            <thead>
              <tr>
                <th>Asset / surface</th>
                {tm.stride_matrix.letters_present.map((L) => <th key={L}>{L}</th>)}
              </tr>
            </thead>
            <tbody>
              {tm.stride_matrix.rows.map((row) => (
                <tr key={row.asset}>
                  <td>{row.asset}</td>
                  {tm.stride_matrix.letters_present.map((L) => {
                    const v = row.cells[L];
                    return <td key={L}><span className={`matrix-cell matrix-cell--${MATRIX_CLASS[v]}`}>{MATRIX_LABEL[v]}</span></td>;
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="legend">
          <span><span className="legend__swatch" style={{ background: "var(--cell-covered)" }} />covered — mitigated</span>
          <span><span className="legend__swatch" style={{ background: "var(--cell-both)" }} />partial — some mitigated</span>
          <span><span className="legend__swatch" style={{ background: "var(--cell-gapped)" }} />gap — no mitigation</span>
          <span><span className="legend__swatch" style={{ background: "var(--cell-silent)" }} />silent — not modeled</span>
        </div>
      </section>

      {/* B — entries table */}
      <section>
        <div className="section-eyebrow" style={{ marginTop: "var(--space-5)" }}>B — Threat entries</div>
        <table className="attack-table">
          <thead>
            <tr><th>Asset</th><th>Threat</th><th>STRIDE</th><th>Mitigation</th><th>Conf.</th><th>APD goals</th><th>Source</th></tr>
          </thead>
          <tbody>
            {tm.entries.map((e, i) => (
              <tr key={i}>
                <td style={{ color: "var(--ink)" }}>{e.asset}</td>
                <td>{e.threat}</td>
                <td><span className="mono">{e.stride_letter || e.linddun_letter || "—"}</span></td>
                <td>{e.mitigation
                  ? e.mitigation
                  : <span style={{ color: "var(--sev-high)", fontSize: "var(--text-xs)", fontFamily: "var(--font-mono)" }}>— none</span>}</td>
                <td><span className="mono">{e.confidence || "—"}</span></td>
                <td><div className="tagrow">{(e.apd_goals || []).map((g) => (
                  <span key={g} className="pill">{(window.GOAL_LABELS || {})[g] || g}</span>
                ))}</div></td>
                <td style={{ fontSize: "var(--text-xs)", color: "var(--ink-3)" }} className="mono">{e.source_locator || "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {/* C — coverage by surface (only when the evaluator ran) */}
      {tm.surface_coverage && (
        <section>
          <div className="section-eyebrow" style={{ marginTop: "var(--space-5)" }}>C — Coverage by surface</div>
          <p style={{ color: "var(--ink-2)", fontSize: "var(--text-sm)", marginBottom: "var(--space-3)" }}>
            Evaluator examined {tm.surface_coverage.summary.surfaces_examined || tm.surface_coverage.rows.length} surface(s) —{" "}
            {tm.surface_coverage.summary.coverage_gaps_emitted || 0} coverage gap(s),{" "}
            {tm.surface_coverage.summary.contradictions_emitted || 0} contradiction(s),{" "}
            {tm.surface_coverage.summary.silences_emitted || 0} silence(s).
          </p>
          <table className="attack-table">
            <thead>
              <tr><th>Surface</th><th>Categories present</th><th>Absent</th><th className="num">Entries</th><th>Coverage</th></tr>
            </thead>
            <tbody>
              {tm.surface_coverage.rows.map((r) => {
                const present = r.present.length, absent = r.absent.length;
                return (
                  <tr key={r.surface}>
                    <td style={{ color: "var(--ink)" }}>{r.surface}</td>
                    <td><div className="tagrow">{r.present.map((c) => <span key={c} className="mono">{c}</span>)}</div></td>
                    <td><div className="tagrow">{r.absent.length
                      ? r.absent.map((c) => <span key={c} className="mono" style={{ color: "var(--ink-3)" }}>{c}</span>)
                      : <span style={{ color: "var(--ink-3)" }}>—</span>}</div></td>
                    <td className="num">{r.entry_count}</td>
                    <td><div className="coverage-bar">
                      <span className="seg-covered" style={{ flex: present }} />
                      <span className="seg-gapped" style={{ flex: absent }} />
                    </div></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>
      )}

      {/* D — trust-boundary surface map */}
      {tm.surface_mermaid && (
        <section>
          <div className="section-eyebrow" style={{ marginTop: "var(--space-5)" }}>D — Surface map</div>
          <MermaidGraph source={tm.surface_mermaid} idBase="apd-tm-surface" />
        </section>
      )}

      {/* E — supplied-vs-authored comparator (only when both TMs exist) */}
      {tm.comparator_delta && (
        <section>
          <div className="section-eyebrow" style={{ marginTop: "var(--space-5)" }}>E — Supplied vs authored</div>
          {[["authored_only", "Authored only — author surfaced, not in supplied TM"],
            ["supplied_only", "Supplied only — in your TM, author did not surface"],
            ["corroborated", "Corroborated — present in both"]].map(([key, label]) => (
            <div key={key} className="contradiction">
              <div className="contradiction__col">
                <div className="contradiction__label">{label} ({tm.comparator_delta[key].length})</div>
                {tm.comparator_delta[key].map((x, i) => (
                  <div key={i} className="contradiction__assertion">{x.asset}: {x.threat}</div>
                ))}
              </div>
            </div>
          ))}
        </section>
      )}
    </div>
  );
}

window.ThreatModel = ThreatModel;
